### ISSUE TITLE
Portfolios do not allow configurable EndUserGroup

### ISSUE THREAD

**Issue by tthyer** [Sage-Bionetworks/service-catalog-library#8]
The portfolios as currently written assume there will be one end user group. Also, the portfolios have the parameter "CreateEndUsers" and then plenty of logic to create the end user group if it does not already exist. 

This is problematic when you may want different user tiers.
It is also problematic if you want to easily show/hide a portfolio. If we create a new parameter "EndUserGroup" that is configurable, we can have multiple user tiers and easily who/hide portfolios.

Since we are now using imports in our library we can move the creation of our user groups elsewhere and import the values. As a temporary measure we can just set "CreateEndUsers" to "No" , but the real work to be done is to refactor the following portfolios to use the EndUserGroup setting and to remove the creation of the group within those portfolios: 

- ec2/sc-portfolio-ec2.yaml
- ec2/sc-portfolio-ec2demo.yaml
- ec2/sc-portfolio-ec2VPC.yaml
- ecs/sc-portfolio-ecs.yaml
- emr/sc-portfolio-emr.yaml
- glue/sc-portfolio-glue.yaml
- rds/sc-portfolio-rds.yaml
- s3/sc-portfolio-s3.yaml
- serverless/sc-portfolio-serverless.yaml
- vpc/sc-portfolio-vpc.yaml

attn @zaro0508

**Comment by tthyer** [comment]
A problem to be solved if we go forward with the refactor is that the current templates avoid the dependency problem.

**Comment by zaro0508** [comment]
this is issue is old and we've implemented multiple portfolios in SC-65
